import { Download } from "lucide-react"
import { jsPDF } from "jspdf"
import type { Detection, RepairSheet } from "@/types"
import { DEFECT_LABELS } from "@/types"
import { cn } from "@/lib/utils"

interface ExportButtonProps {
  detection: Detection
  repairSheet: RepairSheet
  disabled?: boolean
}

export function ExportButton({ detection, repairSheet, disabled }: ExportButtonProps) {
  const handleExport = () => {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    let y = 20

    // Title
    doc.setFontSize(20)
    doc.setFont("helvetica", "bold")
    doc.text("Lazarus - Repair Sheet", pageWidth / 2, y, { align: "center" })
    y += 15

    // Horizontal line
    doc.setDrawColor(200)
    doc.line(20, y, pageWidth - 20, y)
    y += 15

    // Detection Info
    doc.setFontSize(14)
    doc.setFont("helvetica", "bold")
    doc.text("Defect Information", 20, y)
    y += 10

    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    doc.text(`Type: ${DEFECT_LABELS[detection.class]}`, 20, y)
    y += 7
    doc.text(`Confidence: ${(detection.confidence * 100).toFixed(1)}%`, 20, y)
    y += 7
    doc.text(`Position: (${detection.bbox.join(", ")})`, 20, y)
    y += 15

    // Repair Info
    doc.setFontSize(14)
    doc.setFont("helvetica", "bold")
    doc.text("Repair Details", 20, y)
    y += 10

    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    doc.text(`Component: ${repairSheet.component}`, 20, y)
    y += 7
    doc.text(`Defect Type: ${repairSheet.defect_type}`, 20, y)
    y += 7
    doc.text(`Severity: ${repairSheet.severity.toUpperCase()}`, 20, y)
    y += 7
    doc.text(`Estimated Cost: ${repairSheet.estimated_cost}`, 20, y)
    y += 7
    doc.text(`Difficulty: ${"★".repeat(repairSheet.difficulty)}${"☆".repeat(5 - repairSheet.difficulty)}`, 20, y)
    y += 15

    // Repair Steps
    doc.setFontSize(14)
    doc.setFont("helvetica", "bold")
    doc.text("Repair Steps", 20, y)
    y += 10

    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    repairSheet.steps.forEach((step, index) => {
      const lines = doc.splitTextToSize(`${index + 1}. ${step}`, pageWidth - 40)
      lines.forEach((line: string) => {
        if (y > 270) {
          doc.addPage()
          y = 20
        }
        doc.text(line, 20, y)
        y += 7
      })
    })

    // Footer
    y += 10
    doc.setFontSize(9)
    doc.setTextColor(128)
    doc.text(`Generated by Lazarus on ${new Date().toLocaleDateString()}`, pageWidth / 2, 285, { align: "center" })

    // Save
    doc.save(`lazarus-repair-${repairSheet.component.replace(/\s+/g, "-")}.pdf`)
  }

  return (
    <button
      onClick={handleExport}
      disabled={disabled}
      className={cn(
        "w-full flex items-center justify-center gap-2 px-4 py-2 rounded-lg font-medium transition-colors",
        disabled
          ? "bg-gray-100 text-gray-400 cursor-not-allowed"
          : "bg-blue-600 text-white hover:bg-blue-700"
      )}
    >
      <Download className="w-4 h-4" />
      Export PDF
    </button>
  )
}
